Title
Weredok/docs pull request #23
Opened 2022-07-18 19:20 UTC by bridg-dev

2022-07-19 12:24 UTC, WeredokDeveloper requested changes
тут больше переделывать надо

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usddm.md
> +$dm[id?]
пример с неправильным айди

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usddm.md
> +// Возвращает: В личные сообщения бот отправит сообщение
ничего возвращает...

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdhour.md
> +Показывает 1-24 час
показывает который час по ютс часовому поясу

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdimage.md
> +Отправляет изображение
вставляет изображение в встроенное сообщение

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdimage.md
> +$image[$userAvatar[$authorID]]
использование это не пример

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdimage.md
> +| Индекс |  | цифра | Нет |
описание где

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdimage.md
> +// Возвращает: Изображение на вашу аватарку
ничего не возвращает

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdmessageid.md
> +Отправляет ID сообщение
сообщения, которое вызвало эту функцию

2022-07-19 12:24 UTC, WeredokDeveloper commented on functions/usdusername.md
>  $username[userID?]
username(пользователь?)


опции тоже нужно переводить

2022-07-25 20:58 UTC, Weredok commented
когда баг фикс? илимне закрывать запрос?

2022-08-05 21:25 UTC, closed without merging